baseURL: "eshanu00.github.io" 
title: localhost:8080
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Blog
          url: blog/
          weight: 2
        - name: Articles
          url: articles/
          weight: 3

params:
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Blog","Articles"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Eshan J
          subtitle: "This is for learning purpose to get hands on git and github. Working on Progress...."
          imageUrl: "forest.gif"
          imageWidth: 220
          imageHeight: 200
          buttons:
            - name: Blog
              url: blog/
            - name: Articles
              url: articles/

    socialIcons:
        - name: GitHub
          url: https://github.com/eshanu00

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Home"
      icon: icon.png
      iconHeight: 24

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2